### ISSUE TITLE
get rid of promise dependency

### ISSUE THREAD

**Issue by mrgamer** [ForbesLindesay/throat#3]
As io.js 1.x Promises are native into this runtime, so I hope you would lift the dependency.

throat could be required like this:
```javascript
var throat = require('throat')(Promise);

// or in node 0.10.x
var throat = require('throat')(require('promise'));
```

There might be another (with more syntax sugar) versions of this, but this is the simpler that came to mind....

So you can delegate the Promise shim to the user.

**edit:** mmm... #2

**Comment by ForbesLindesay** [comment]
Re #2: times change, Promises are now in core so it makes more sense to use core Promises by default and fall back to making it easy for the user to specify their Promise library of choice.

**Comment by mrgamer** [comment]
nice celerity, as I am really a pedantic person I would ask to make a little release bump so users in npm can get this :)

Thanks a lot!

**Comment by ForbesLindesay** [comment]
It's published now :)  I was just waiting for sauce labs to finish testing all the browsers.
