### ISSUE TITLE
Suggestion of a new type

### ISSUE THREAD

**Issue by lpenaud** [ForbesLindesay/throat#55]
Hi,
I work on a typescript project and I use throat module and it's work well, however when I create a lock and I call it with a function which take a argument my IDE say:
"Expected 1 arguments, but got 2."

Example:
```ts
const arg = "arg";
const lock = throat(1);
lock(func, arg);
```
To avoid this problem I added this line in "index.d.ts":
```ts
declare function throat(size: number): <TResult>(fn: (args?: any) => Promise<TResult>, args?: any) => Promise<TResult>;
```
Then I have no this problem anymore if I write like this:
```ts
const arg = "arg";
const lock = throat<void>(1);
lock(func, arg);
```
If you don't mind, can you add something like this?

Best regard

**Comment by ForbesLindesay** [comment]
Thanks for pointing this out. Please try the newly released throat@5.0.0. The following code should now work fine:

```ts
async function func(arg: string) {}
const lock = throat(1);
lock(func, 'arg')
```
