### ISSUE TITLE
Consider replacing custom promise input with `any-promise`

### ISSUE THREAD

**Issue by blakeembrey** [ForbesLindesay/throat#9]
It's not a huge change, but it is a breaking one. Using `any-promise` as a defacto for `Promise` allows users to set the promise across a number of dependencies as once without customisation required for each. Would you be willing to accept a PR using https://www.npmjs.com/package/any-promise instead of taking a promise function?

**Comment by ForbesLindesay** [comment]
People can just replace the global promise, as long as their implementation is ES6 compatible.  I don't think we need other ways or registering a preferred implementation.
